# --- PUBLIC SAFE DEFAULTS ---
image:
  repository: harbor.cop-pilot.rid-intrasoft.eu/cluster2-upv-waste-management/waste-monitor
  tag: latest
  pullPolicy: Always

# --- APP CONFIGURATION ---
appConfig:
  orionHost: "172.21.32.104"    
  orionPort: "1026"
  entityId: "urn:ngsi-ld:WasteContainer:67-49-e4-49-70-22-00-28"
  telegramBotToken: ""          
  telegramChatId: ""            